# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  DOCKER_IMAGE_ORIGIN_MASTER: "docker.pkg.github.com/openipc/openwrt/buildmaster"
  DOCKER_IMAGE_ORIGIN_SLAVE: "docker.pkg.github.com/openipc/openwrt/buildslave"
  DOCKER_IMAGE_VERSION: "latest"
  REPOSITORY: "chaos_calmer"
  IN_DOCKER_ROOT_FOLDER: "/src/chaos_calmer"
  GITHUB_USER: "ssharshunov"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Login to docker registry
      id: login_reg
      run: |
        # Login to GitHub Packages and build Docker image
        echo ${GITHUB_TOKEN} | docker login https://docker.pkg.github.com -u ${GITHUB_USER} --password-stdin
        docker pull ${DOCKER_IMAGE_ORIGIN}:${DOCKER_IMAGE_VERSION}

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
